#
#   ██████╗ ██╗   ██╗███████╗██╗  ██╗██████╗  ██████╗  █████╗ ██████╗ ██████╗
#   ██╔══██╗██║   ██║██╔════╝██║  ██║██╔══██╗██╔═══██╗██╔══██╗██╔══██╗██╔══██╗
#   ██████╔╝██║   ██║███████╗███████║██████╔╝██║   ██║███████║██████╔╝██║  ██║
#   ██╔══██╗██║   ██║╚════██║██╔══██║██╔══██╗██║   ██║██╔══██║██╔══██╗██║  ██║
#   ██║  ██║╚██████╔╝███████║██║  ██║██████╔╝╚██████╔╝██║  ██║██║  ██║██████╔╝
#   ╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝
# Created by iShift.
# Discord account: iShift#0001
# Discord support server: https://discord.gg/VkfhFCv

# Worlds where the board should display
worlds:
  - world
  - world_nether
  - world_the_end

# Interval in ticks, before next scoreboard refresh.
interval: 20

# Main scoreboard options.
# Each line can have max. 40 characters on 1.8.x.
# Versions above 1.13 can use more characters.
# Lines can't repeat.
# You can use PlaceholderAPI placeholders.
scoreboard:
  # You can fully disable scoreboard, to use this plugin only as API.
  enabled: true
  title: "&e&lRUSHBOARD"
  contents:
    - "&r"
    - "&fYou are using &eRushBoard."
    - "&fChange this in &econfig.yml."
    - "&r&r"
    - "&fPlaceholderAPI Test:"
    - "&e%rushboard_version%"
    - "&r&r&r"
    - "&ewww.spigotmc.org"

# Configure every message available in the plugin.
messages:
  main-command:
    - "&7&m------------------------------------"
    - "     &eRushBoard &7Dostepne komendy"
    - ""
    - "&f/%alias% reload &7- przeladowywuje konfiguracje."
    - "&f/%alias% toggle &7- wylaczanie/wlaczanie scoreboarda."
    - "&7&m------------------------------------"
  no-permission: "&8» &cNie masz uprawnien."
  unknown-command: "&8» &acNieznana komenda."
  reload: "&eRushBoard &8» &7Konfiguracja zostala &apomyslnie &7przeladowana."
  toggled-on: "&eRushBoard &8» &aWlaczyles &7scoreboard"
  toggled-off: "&eRushBoard &8» &cWylaczyles &7scoreboard"
