# Worlds where board should display
worlds:
  - world
  - world_nether
  - world_the_end

# Interval in ticks, before next scoreboard refresh.
interval: 20

# Main scoreboard options.
# Each line can have max. 40 characters on 1.8.x.
# Versions above 1.13 can use more characters.
# Lines can't repeat.
# You can use PlaceholderAPI placeholders.
scoreboard:
  # You can fully disable scoreboard, to use this plugin only as API.
  enabled: true
  title: "&e&lRUSHBOARD"
  contents:
    - "&r"
    - "&fYou are using &eRushBoard."
    - "&fChange this in &econfig.yml."
    - "&r&r"
    - "&fPlaceholderAPI Test:"
    - "&e%rushboard_version%"
    - "&r&r&r"
    - "&ewww.spigotmc.org"

# Configure every message available in the plugin.
messages:
  main-command:
    - "&m------------------------------------"
    - "&eRushBoard &7Help command"
    - ""
    - "&f/%alias% reload &7- reload configuration."
    - "&f%alias% toggle &7- hide/reappear sidebar for you."
    - "&m------------------------------------"
  no-permission: "&cYou don't have permission to do this."
  unknown-command: "&cCommand not found."
  reload: "&eRushBoard &7has been &asuccesully &7reloaded."
  toggle-on: "&7You have toggled &aON &7your scoreboard."
  toggle-off: "&7You have toggled &cOFF &7your scoreboard."